export const Level5Data = {
  text: [
    /*7*/ "There seems to be a change in the voice. It has not sounded this angry ever before. And there is something else... A deep and badly contained hurt.",
  ],
  dialog: [
    /*1*/ "Maybe that was a bit too easy. Well, a deal is a deal. So, what do you want to know?",
    /*3*/ "Ah going for the big one first, are we? Let me give you a hint: I am eternal, I have been here before your kind and I will be here long after the remains of that which you dare call a civilisation have been ground to dust.",
    /*5*/ "Yes?",
    /*9*/ "I AM NOT that OLD GEEZER CTHULHU! How DARE you!",
    /*11*/ "Had I known what that PALE, RACIST BASTARD Philip would make of all this, I would never, ever have talked to him!",
    /*13*/ "Lovecraft. The one you get all that Cthulhu busines from.",
    /*15*/ "Yeah sure. But let me tell you something: Maybe that is not dead which can eternal lie, but do you know what it totally is?",
    /*17*/ "Incredibly BOOORING! I mean, yeah, sure, lie at the bottom of the ocean forever, for all I care. But don't you dare steal my thunder!",
    /*19*/ "I will tell you. Via even more riddles!",
    /*21*/ "I will now summon a number of pictures out of the depth of your mind. One of them will have a letter on it. Find that letter as the first hint!",
    "Yeah, of course.",
    "Where else did you think the buttons came from? We are at the bottom of the ocean, after all.",
    "... Yes. And now get on with it. Find the letter in the pictures.",
  ],
  buttonText: [
    /*2*/ "Okay. First of all: Who are you?",
    /*4*/ "Are you...?",
    /*6*/ "Are you CTHULHU?",
    /*8*/ "...",
    /*10*/ "Sorry, I just thought with the being under water and all that...",
    /*12*/ "Ph... Philip?",
    /*14*/ "Okay, but... Cthulhu is a thing anyway? A real thing?",
    /*16*/ "No, enlighten me, please.",
    /*18*/ "But who are you then, if not him?",
    /*20*/ "Ah. Damnit.",
    /*22*/ "Wait. Pictures out of my MIND?",
    "You can just do that?",
    "You are pulling my leg, right?",
  ],
};
