export const level1Data = {
  text: [
    /*0*/ "You do it. Without further thinking, you do it. As you leap over the side of your boat, for a moment the doubt hits you. What could lie beneath these dark waves?",
    /*1*/ "But too late. A splash and the muddy waters close over your head. And then you begin to drop. You have been diving before. The familiar feeling overtakes you as you slowly descend.",
    /*2*/ "And then, suddenly, the feeling is not that familiar anymore. And you are no longer dropping. Now you are beeing pulled. A frantic look out of your helmet in the direction of your feet reveals... nothing. But that is impossible! You can feel it, the pull, the drag towards the ocean floor!",
    /*3*/ "You are about to panic, but before the fear can wash over you, you hit the ground. Too fast. The ocean should be way deeper here. Or... Were you dragged down so fast, that what should have taken minutes is over in seconds?",
    /*4*/ "Whatever the reason, the shock of the impact shakes you out of the onset of panic.",
    /*5*/ "And then... A voice in the dark. A voice? Down here? What should be impossible rings loud and clear in your ears.",
    /*6*/ "No, not in your ears. In your head. In your MIND.",
  ],
  dialog: [
    "Aaaaah... You did it, did you? Jumped right into the cold, the dark. Just following your curiosity... You humans are just so... Predictable...",
    "And now you are here. With me. With ME.",
    "ph'nglui mglw'nafh Cthulhu R'lyeh wgah'nagl fhtagn!",
    "*Cough, cough*",
    "I am so sorry. I had something stuck in my throat. Again, very sorry for the weird sounds.",
    "Yeah? So what? I am not allowed to have something stuck in my throat? Just because I am a disembodied voice? That seems a little reductionist of you, don't you think?",
    "That's what I thought. Besides, I am obviously *not* disembodied. That is, again, so very human of you. 'Oh, I cannot see who is talking, so clearly the speaker must be a *DISEMBODIED VOICE*.'",
    "Yeah, yeah, of course you didn't. Your kind never does. You never *mean* anything by anything. You just do. And all of a sudden everything is broken and it's nobodies fault, because nobody *meant* anything.",
    "Of course I am angry! But the good thing is: Now I have someone to vent all my anger on!",
    "Oh yes! YOU!",
    "That might be true, might not be true. But the fact is: You are here and I am here. So it is going to be YOU.",
    "Oh, you poor thing. I am gonna do things to you so much worse than any torture your small mind could ever conceive of! I am going to...",
    "",
    "That was a good pause, wasn't it? Pauses always increase the antici...",
    "...pation. Alright, alright.",
    "Press the big red button please.",
    "What are you talking about? There is a very visible red button right in front of you! It is red!",
    "Pff. 'Shouldn't be'. You people are ridiculous. Talking about 'shouldn't' when there quite obviously *is*.",
    "I know, I know. If it gives you peace of mind, lets say the button is just in your head, alright?",
    "Well, that's what you're getting. So. Would you kindly press the big red button now?",
  ],
  buttonText: [
    "Go on...",
    "Okay.",
    "What?",
    "This is weird.",
    "Alright?",
    "...",
    "...",
    "But...",
    "Come again?",
    "...",
    "Your throat? But you are a disembodied voice in my mind, aren't you?",
    "Nevermind...",
    "Sorry, I didn't mean to...",
    "You seem... Angry?",
    "Oh no...",
    "But I didn't do anything!",
    "What are you going to do to me? Are you going to torture me?",
    "What?",
    "Are you still there?",
    "You are *not* going to pull a Frankenfurter on me!",
    "So what now?",
    "We are in the ocean. There is no button.",
    "Yes but there shouldn't be! We are, again, in the ocean!",
    "But...",
    "That isn't really better...",
  ],
};
